# Generated by Django 5.1.2 on 2024-10-23 12:01

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Hyderabad', 'HYDERABAD')], default='Hyderabad', max_length=150)),
                ('area', models.CharField(choices=[('ALWAL', 'ALWAL'), ('AMBERPET', 'AMBERPET'), ('AMEERPET', 'AMEERPET'), ('ATTAPUR', 'ATTAPUR'), ('BACHUPALLY', 'BACHUPALLY'), ('BANJARA HILLS', 'BANJARA_HILLS'), ('BEGUMPET', 'BEGUMPET'), ('CHARMINAR', 'CHARMINAR'), ('DILSUKHNAGAR', 'DILSUKHNAGAR'), ('ECIL', 'ECIL'), ('GACHIBOWLI', 'GACHIBOWLI'), ('HAFIZ BABA NAGAR', 'HAFIZ_BABA_NAGAR'), ('HAYATH NAGAR', 'HAYATH_NAGAR'), ('HIMAYATNAGAR', 'HIMAYATNAGAR'), ('JEEDIMETLA', 'JEEDIMETLA'), ('JNTU', 'JNTU'), ('KARKHANA', 'KARKHANA'), ('KOMPALLY', 'KOMPALLY'), ('KONDAPUR', 'KONDAPUR'), ('KUKATPALLY', 'KUKATPALLY'), ('LB NAGAR', 'LB_NAGAR'), ('MADHAPUR', 'MADHAPUR'), ('MALAKPET', 'MALAKPET'), ('MANIKONDA', 'MANIKONDA'), ('MASAB TANK', 'MASAB_TANK'), ('MEDCHAL ROAD', 'MEDCHAL_ROAD'), ('MIYAPUR', 'MIYAPUR'), ('MOKILA', 'MOKILA'), ('MOOSAPET', 'MOOSAPET'), ('NAGOLE', 'NAGOLE'), ('NARAYANGUDA', 'NARAYANGUDA'), ('NIZAMPET', 'NIZAMPET'), ('PATANCHERU', 'PATANCHERU'), ('PEERZADIGUDA', 'PEERZADIGUDA'), ('Q CITY', 'Q_CITY'), ('SAINIKPURI', 'SAINIKPURI'), ('SANGAREDDY', 'SANGAREDDY'), ('SAROOR NAGAR', 'SAROOR_NAGAR'), ('SERILINGAMPALLY', 'SERILINGAMPALLY'), ('SHAMSHABAD', 'SHAMSHABAD'), ('SIVARAMPALLI', 'SIVARAMPALLI'), ('SURARAM', 'SURARAM'), ('TARNAKA', 'TARNAKA'), ('TOLI CHOWKI', 'TOLI_CHOWKI'), ('UPPAL', 'UPPAL'), ('VANASTHALIPURAM', 'VANASTHALIPURAM')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, related_name='wallefy_backend_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='wallefy_backend_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LocationWiseCategoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rent_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Food_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Shopping_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Travelling_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Health_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Entertainment_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Savings_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Miscellaneous_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=10)),
                ('preference', models.CharField(choices=[('RICH', 'RICH'), ('MIDDLE CLASS', 'MIDDLE_CLASS'), ('POOR', 'POOR')], max_length=150)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallefy_backend.location')),
            ],
        ),
        migrations.CreateModel(
            name='UserExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Food', 'FOOD'), ('Entertainment', 'ENTERTAINMENT'), ('Travel', 'TRAVEL'), ('Health', 'HEALTH'), ('Miscellaneous', 'MISCELLANEOUS'), ('Rent', 'RENT'), ('Savings', 'SAVINGS'), ('Shopping', 'SHOPPING'), ('Income', 'INCOME'), ('Expense', 'EXPENSE')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('expenses_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferenceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField(auto_now=True)),
                ('preference', models.CharField(choices=[('RICH', 'RICH'), ('MIDDLE CLASS', 'MIDDLE_CLASS'), ('POOR', 'POOR')], max_length=150)),
                ('location', models.CharField(choices=[('ALWAL', 'ALWAL'), ('AMBERPET', 'AMBERPET'), ('AMEERPET', 'AMEERPET'), ('ATTAPUR', 'ATTAPUR'), ('BACHUPALLY', 'BACHUPALLY'), ('BANJARA HILLS', 'BANJARA_HILLS'), ('BEGUMPET', 'BEGUMPET'), ('CHARMINAR', 'CHARMINAR'), ('DILSUKHNAGAR', 'DILSUKHNAGAR'), ('ECIL', 'ECIL'), ('GACHIBOWLI', 'GACHIBOWLI'), ('HAFIZ BABA NAGAR', 'HAFIZ_BABA_NAGAR'), ('HAYATH NAGAR', 'HAYATH_NAGAR'), ('HIMAYATNAGAR', 'HIMAYATNAGAR'), ('JEEDIMETLA', 'JEEDIMETLA'), ('JNTU', 'JNTU'), ('KARKHANA', 'KARKHANA'), ('KOMPALLY', 'KOMPALLY'), ('KONDAPUR', 'KONDAPUR'), ('KUKATPALLY', 'KUKATPALLY'), ('LB NAGAR', 'LB_NAGAR'), ('MADHAPUR', 'MADHAPUR'), ('MALAKPET', 'MALAKPET'), ('MANIKONDA', 'MANIKONDA'), ('MASAB TANK', 'MASAB_TANK'), ('MEDCHAL ROAD', 'MEDCHAL_ROAD'), ('MIYAPUR', 'MIYAPUR'), ('MOKILA', 'MOKILA'), ('MOOSAPET', 'MOOSAPET'), ('NAGOLE', 'NAGOLE'), ('NARAYANGUDA', 'NARAYANGUDA'), ('NIZAMPET', 'NIZAMPET'), ('PATANCHERU', 'PATANCHERU'), ('PEERZADIGUDA', 'PEERZADIGUDA'), ('Q CITY', 'Q_CITY'), ('SAINIKPURI', 'SAINIKPURI'), ('SANGAREDDY', 'SANGAREDDY'), ('SAROOR NAGAR', 'SAROOR_NAGAR'), ('SERILINGAMPALLY', 'SERILINGAMPALLY'), ('SHAMSHABAD', 'SHAMSHABAD'), ('SIVARAMPALLI', 'SIVARAMPALLI'), ('SURARAM', 'SURARAM'), ('TARNAKA', 'TARNAKA'), ('TOLI CHOWKI', 'TOLI_CHOWKI'), ('UPPAL', 'UPPAL'), ('VANASTHALIPURAM', 'VANASTHALIPURAM')], max_length=150)),
                ('city', models.CharField(choices=[('Hyderabad', 'HYDERABAD')], default='hyderabad', max_length=150)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Student', 'STUDENT'), ('Employee', 'EMPLOYEE')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
